=== CryptoMathician/dns_load_balancer_server/dns_load_balancer_server/Settings.xsd
<?xml version="1.0" encoding="ISO-8859-1"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

<xs:element name="setting">
 <xs:complexType>
  <xs:sequence>
	<xs:element name="limit" type="xs:int" />
	<xs:element name="config_path" type="xs:string"/>
	<xs:element name="xml" type="xs:string" />
	<xs:element name="xsd" type="xs:string" />
	<xs:element name="dbxml" type="xs:string"/>
	<xs:element name="dbxsd" type="xs:string"/>
	<xs:element name="server_port" type="xs:int"/>
	<xs:element name="admin_server_port" type="xs:int"/>
   </xs:sequence>
  </xs:complexType>
 </xs:element>
</xs:schema>

=== CryptoMathician/dns_load_balancer_server/dns_load_balancer_server/Settings.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<setting xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Settings.xsd">
<limit>60</limit>
<config_path>/etc/dns_load_balancer</config_path>
<xml>TSInfo.xml</xml>
<xsd>TSInfo.xsd</xsd>
<dbxml>db_conf.xml</dbxml>
<dbxsd>db_conf.xsd</dbxsd>
<server_port>20500</server_port>
<admin_server_port>20510</admin_server_port>
</setting>
